# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    ignore:
      # Ignore major updates for 11ty packages
      - dependency-name: "@11ty/*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all npm updates together
      npm-packages:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore minor and patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    groups:
      # Group all updates together
      github-actions:
        patterns:
          - "*"
