title: Data.gov
description: >- # this means to ignore newlines
  The home of the U.S. Government&#8217;s open data. 
  Here you will find data, tools, and resources to conduct research, develop web and 
  mobile applications, design data visualizations, and more. For information regarding the 
  Coronavirus/COVID-19, please visit Coronavirus.gov
locale: en_US
# Social media handles. Only the handle, not the URL.
twitter: usdatagov
github: GSA/data.gov

#################################################################
#
# Digital Analytics Program (DAP) configuration
#
# USAID   - Agency for International Development
# USDA    - Department of Agriculture
# DOC     - Department of Commerce
# DOD     - Department of Defense
# ED      - Department of Education
# DOE     - Department of Energy
# HHS     - Department of Health and Human Services
# DHS     - Department of Homeland Security
# HUD     - Department of Housing and Urban Development
# DOJ     - Department of Justice
# DOL     - Department of Labor
# DOS     - Department of State
# DOI     - Department of the Interior
# TREAS   - Department of the Treasury
# DOT     - Department of Transportation
# VA      - Department of Veterans Affairs
# EPA     - Environmental Protection Agency
# EOP     - Executive Office of the President
# GSA     - General Services Administration
# NASA    - National Aeronautics and Space Administration
# NARA    - National Archives and Records Administration
# NSF     - National Science Foundation
# NRC     - Nuclear Regulatory Commission
# OPM     - Office of Personnel Management
# USPS    - Postal Service
# SBA     - Small Business Administration
# SSA     - Social Security Administration
#
#################################################################
dap:
  agency: GSA

  # Optional
  # subagency: your-subagency

# Configuration for Google Analytics
ga:
  gtm: GTM-WZJC8CX7

# Site Navigation
primary_navigation:
  - name: Data
    url: https://catalog.data.gov
  - name: Metrics
    url: /metrics
  - name: Open Government
    url: /open-gov
  - name: Contact
    url: /contact

links:
  sites:
    resources: https://resources.data.gov
    strategy: https://strategy.data.gov
  social:
    twitter: https://twitter.com/usdatagov
    github: https://github.com/GSA/data.gov

catalog_filters:
  - name: Most Viewed Datasets
    url: https://catalog.data.gov/dataset?q=&sort=views_recent+desc
    iconName: most-viewed-datasets-icon
  - name: Recently Added Datasets
    url: https://catalog.data.gov/dataset?q=&sort=metadata_created+desc
    iconName: recently-added-datasets-icon
  - name: Datasets by Organization
    url: https://catalog.data.gov/organization/
    iconName: organizations-datasets-icon
  - name: Geospatial
    url: https://catalog.data.gov/dataset/?metadata_type=geospatial
    iconName: geospatial-icon

resource_quick_links:
  - title: Data Management & Governance
    url: https://resources.data.gov/categories/data-management-governance/
  - title: Data Tools
    url: https://resources.data.gov/categories/data-tools/
  - title: Data Incubator
    url: https://resources.data.gov/categories/data-incubator/
  - title: Guidance
    url: https://resources.data.gov/categories/guidance/
  - title: Case Studies & Examples
    url: https://resources.data.gov/categories/case-studies-examples/
  - title: Skills Development
    url: https://resources.data.gov/categories/skills-development/

strategy_quick_links:
  - title: 2021 Action Plan
    url: https://strategy.data.gov/2021/action-plan/
  - title: 2020 Action Plan
    url: https://strategy.data.gov/2020/action-plan/
  - title: 2021 Action Progress
    url: https://strategy.data.gov/2021/progress/
  - title: 2020 Action Progress
    url: https://strategy.data.gov/2020/progress/

about_page_hero_icons:
  - title: Inform decisions
    url: inform-decisions.png
  - title: Drive innovation
    url: drive-innovation.png
  - title: Achieve agency missions
    url: agency-missions.png
  - title: Strengthen open government
    url: strengthen-government.png
